### ISSUE TITLE
Depends on version 1.22 of warnings, but minimum version of perl is 5.10

### ISSUE THREAD

**Issue by jwrightecs** [kimryan/Lingua-EN-Sentence#3]
Module requires warnings 1.22 (from 5.19.9) limiting it to be being installable on perls 5.20 and higher, but it also depends on perl minimum version 5.10, where it is not installable due to the warnings version requirement.

**Comment by kimryan** [comment]
So would the follwing changfe to Build.PL fix this?
 requires =>
 {
   perl                => 5.20,
   warnings        => 1.22
 },

**Comment by jwrightecs** [comment]
or perl => 5.10, warnings => 1.06

**Comment by kimryan** [comment]
Fixed in 0.33
